### ISSUE TITLE
Rails generator

### ISSUE THREAD

**Issue by technicalpickles** [tobi/delayed_job#8]
It seems that a user of delayed_job is always going to need to make a migration for the delayed_jobs table. It would make sense to provide a generator to automate this process.

I've made a small one in my fork: http://github.com/technicalpickles/delayed_job/tree/generator

**Comment by richievos** [comment]
Not sure if/when this was merged in, but you can now say script/generate delayed and this happens automagically.

**Comment by technicalpickles** [comment]
Are you sure? I'm looking at the upstream repo, and not seeing any code related to a generator.

**Comment by richievos** [comment]
I'll take a closer look tomorrow, the reason I say so is this morning I was in my repo and tried script/generate delayed and it worked and generated a migration for me. I'll try and track down where it came from.

**Comment by richievos** [comment]
In looking through my system I have the delayed_job gem installed (which is ironic since I was asking tobi earlier if he was going to push one). From other discussions I was informed that gem is actually based on the collectiveidea fork. Looking at that code there is a generator there. So, my guess is though I'm using tobi's fork/gem, script/generate picked up on the other gem's generator.

Summary being, I stand corrected (2nd time today), but the collectiveidea fork has it if you're interested.
